/**
 * The audited event vocabulary (§16.1).
 *
 * Not in @sora/contracts because no client consumes it as a request or
 * response value — the mobile app never sends an event name. It is read back
 * only through GET /wallets/{id}/audit-logs, whose rows carry the string as
 * data.
 */

export const AUDIT_EVENTS = {
  USER_REGISTERED: 'USER_REGISTERED',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGOUT: 'USER_LOGOUT',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  /** A revoked refresh token was presented, i.e. replayed — every session ended. */
  TOKEN_REPLAY_DETECTED: 'TOKEN_REPLAY_DETECTED',

  /** A member's request refused with 403; a 404 is not recorded, since no membership resolved. */
  ACCESS_DENIED: 'ACCESS_DENIED',

  WALLET_CREATED: 'WALLET_CREATED',
  WALLET_UPDATED: 'WALLET_UPDATED',
  WALLET_ARCHIVED: 'WALLET_ARCHIVED',
  WALLET_OWNERSHIP_TRANSFERRED: 'WALLET_OWNERSHIP_TRANSFERRED',

  MEMBER_INVITED: 'MEMBER_INVITED',
  MEMBER_REMOVED: 'MEMBER_REMOVED',
  MEMBER_LEFT: 'MEMBER_LEFT',
  MEMBER_ROLE_CHANGED: 'MEMBER_ROLE_CHANGED',
  INVITATION_ACCEPTED: 'INVITATION_ACCEPTED',
  INVITATION_REVOKED: 'INVITATION_REVOKED',

  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  ACCOUNT_UPDATED: 'ACCOUNT_UPDATED',
  ACCOUNT_ARCHIVED: 'ACCOUNT_ARCHIVED',

  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_ARCHIVED: 'CATEGORY_ARCHIVED',
  /** mode=permanent (§10.4) — distinct from CATEGORY_ARCHIVED so the trail says which one happened. */
  CATEGORY_DELETED: 'CATEGORY_DELETED',

  TRANSACTION_CREATED: 'TRANSACTION_CREATED',
  TRANSACTION_UPDATED: 'TRANSACTION_UPDATED',
  /** Status flip only (BR-03) — the row is never removed, unlike CATEGORY_DELETED above. */
  TRANSACTION_DELETED: 'TRANSACTION_DELETED',

  BUDGET_CREATED: 'BUDGET_CREATED',
  BUDGET_UPDATED: 'BUDGET_UPDATED',
  BUDGET_DELETED: 'BUDGET_DELETED',

  GOAL_CREATED: 'GOAL_CREATED',
  GOAL_UPDATED: 'GOAL_UPDATED',
  GOAL_CANCELLED: 'GOAL_CANCELLED',
  GOAL_CONTRIBUTION_ADDED: 'GOAL_CONTRIBUTION_ADDED',
  GOAL_CONTRIBUTION_REMOVED: 'GOAL_CONTRIBUTION_REMOVED',
} as const;

export type AuditEvent = (typeof AUDIT_EVENTS)[keyof typeof AUDIT_EVENTS];

export const ENTITY_TYPES = {
  USER: 'USER',
  SESSION: 'SESSION',
  WALLET: 'WALLET',
  WALLET_MEMBER: 'WALLET_MEMBER',
  WALLET_INVITATION: 'WALLET_INVITATION',
  ACCOUNT: 'ACCOUNT',
  CATEGORY: 'CATEGORY',
  TRANSACTION: 'TRANSACTION',
  BUDGET: 'BUDGET',
  GOAL: 'GOAL',
  GOAL_CONTRIBUTION: 'GOAL_CONTRIBUTION',
} as const;

export type EntityType = (typeof ENTITY_TYPES)[keyof typeof ENTITY_TYPES];
